name: Build Wheel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-python-packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: uv sync

    - name: Build wheel
      run: uv run build

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/*.whl

    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz
