on:
  workflow_run:
    workflows: ["Build artifacts"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v3
        with:
          # This name must match the value in build.yml
          name: python_packages.zip
          path: ./downloads

      - name: Unzip python packages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p dist
          unzip downloads/python_packages.zip -d dist

      - name: Upload files to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: dist/*
